services:
  app:
    build: ./app
    ports:
      - "8080:80"
    volumes:
      - ${PWD}:/app/public
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:admin@db:3306/db

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    env_file: ./.env.local
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
volumes:
  db_data: